fn main() {
  // Declared unconditionally (not #[cfg]'d per edition) — this list only
  // drives permission-scaffold generation (src-tauri/permissions/autogenerated/
  // + what capabilities/*.json is allowed to reference), independent of
  // which of these commands is actually compiled into a given edition's
  // binary (see the #[cfg(not(feature = "appstore"))] / #[cfg(feature =
  // "appstore")] split in src/lib.rs). Keeping the union here means both
  // editions' permission files always exist, so capabilities/default.json
  // doesn't need its own per-edition variant.
  tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
    tauri_build::AppManifest::new().commands(&[
      // direct edition
      "open_login_window",
      "close_login_window",
      "zhihu_fetch",
      "zhihu_fetch_result",
      "zhihu_me",
      "wait_for_login",
      "logout",
      "check_login_status",
      // appstore edition
      "save_access_secret",
      "has_access_secret",
      "get_access_secret",
      "clear_access_secret",
      // shared
      "resize_main_window",
    ]),
  ))
  .expect("failed to run tauri-build");
}
