import test from "node:test"; import assert from "node:assert/strict"; import {mkdtemp, mkdir, writeFile} from "node:fs/promises"; import os from "node:os"; import path from "node:path"; import {safeName,isoDate,assertSafeEmptyOutputDir} from "../src/util.js";
import { imageFileName, normalizeImageSources } from "../src/exporter.js";
test("safeName removes unsafe filename characters",()=>assert.equal(safeName('a/b:c*?"<>|'),"a_b_c______"));
test("isoDate converts epoch seconds",()=>assert.equal(isoDate(0),"1970-01-01T00:00:00.000Z"));
test("different image bytes never share a filename",()=>assert.notEqual(imageFileName(Buffer.from("image-a"),"image/jpeg"),imageFileName(Buffer.from("image-b"),"image/jpeg")));
test("identical image bytes deduplicate across URLs",()=>assert.equal(imageFileName(Buffer.from("same"),"image/png"),imageFileName(Buffer.from("same"),"image/png; charset=binary")));
test("lazy image uses the real source instead of SVG placeholder",()=>assert.equal(normalizeImageSources(`<img src="data:image/svg+xml,x" data-actualsrc="https://pic.zhimg.com/real.jpg" alt="图">`),`<img src="https://pic.zhimg.com/real.jpg" alt="图">`));
test("placeholder-only image is removed",()=>assert.equal(normalizeImageSources(`<img src="data:image/svg+xml,x">`),""));
test("noscript fallback does not duplicate a lazy image",()=>assert.equal(normalizeImageSources(`<img src="data:image/svg+xml,x" data-actualsrc="https://pic.zhimg.com/real.jpg"><noscript><img src="https://pic.zhimg.com/real.jpg"></noscript>`),`<img src="https://pic.zhimg.com/real.jpg">`));
test("output safety allows a missing directory",async()=>{const base=await mkdtemp(path.join(os.tmpdir(),"archive-test-"));await assert.doesNotReject(assertSafeEmptyOutputDir(path.join(base,"new"),[],[]));});
test("output safety rejects a non-empty directory",async()=>{const base=await mkdtemp(path.join(os.tmpdir(),"archive-test-"));const out=path.join(base,"out");await mkdir(out);await writeFile(path.join(out,"existing.txt"),"x");await assert.rejects(assertSafeEmptyOutputDir(out,[],[]),/不是空目录/);});
test("output safety rejects protected descendants",async()=>{const base=await mkdtemp(path.join(os.tmpdir(),"archive-test-"));await assert.rejects(assertSafeEmptyOutputDir(path.join(base,"private","child"),[],[path.join(base,"private")]),/受保护/);});
